name: flutter_gearbox
description: Flutter Gearbox with all utility functions (extensions, logger, navigator, network, custom screen, snackbar, spaces, status_code, custom_text_field, url_launcher)
version: 0.0.2
homepage: https://github.com/swarajkumarsingh/flutter_gearbox

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  internet_connection_checker: ^1.0.0+1
  logger: ^1.3.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

following page: https://dart.dev/tools/pub/pubspec

flutter:
